### ISSUE TITLE
Chaotic analog stick movement caused by reverted bit order

### ISSUE THREAD

**Issue by prk3** [StarGate01/ArduinoPSX#2]
Hi! First of all, it's impressive how concise the code is, considering that it communicates with a PS2 controller flawlessly. Great work!

I noticed that the order of bits in data read from the controller is reverted. The controller sends the least significant bit first, but the library saves it at the most significant position. Because of that, analog stick positions seem to change completely at random instead of changing linearly. This should be fixed either by reverting bit order before saving positions in `buttons.JoyLeftX` or by fixing the read order and adjusting all constants in the library.

For people interested, the order of bits in a byte can be easily reverted using the following function:
```c++
byte reverted(byte b) {
  return
    ((b & 0b10000000) >> 7) |
    ((b & 0b01000000) >> 5) |
    ((b & 0b00100000) >> 3) |
    ((b & 0b00010000) >> 1) |
    ((b & 0b00001000) << 1) |
    ((b & 0b00000100) << 3) |
    ((b & 0b00000010) << 5) |
    ((b & 0b00000001) << 7);
}
```

Edit: updated revert code.

**Comment by StarGate01** [comment]
Thank you very much for this, I fixed it.

Fun fact: The return value that should ensure that the data is valid is `0x5A` or `0b01011010`, which is the same from both directions. That's why I did not catch this error in 2016, I just assumed my controller was janky.

I also took the opportunity and added an example and documentation.
